hydra:
  run:
    # keep Hydra from creating a new working dir for each run; makes output easier to read
    dir: .

earthdata_access:
  username: "your_edl_username"
  password: "your_edl_password"

selection:
  date_min: '2025-11-01'
  date_max: '2025-11-01'

dataset_names:
  - "/FS/Latitude"
  - "/FS/Longitude"
  - "/FS/VER/sigmaZeroNPCorrected"
  - "/FS/ScanTime/Year"
  - "/FS/ScanTime/Month"
  - "/FS/ScanTime/DayOfMonth"
  - "/FS/ScanTime/DayOfYear"
  - "/FS/ScanTime/Hour"
  - "/FS/ScanTime/Minute"
  - "/FS/ScanTime/Second"
  - "/FS/ScanTime/MilliSecond"

partial_mirror:
  rootdir: "~/b2_remote_sensing/gpm_dpr_partial_mirror"
